[build]
  publish = "public"
  command = "npm run build:netlify"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"
  external_node_modules = ["@hono/node-server"]
  node_bundler = "esbuild"