[build]
cmd = "npm run install:all && npm run build"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[variables]
NODE_ENV = "production"
PORT = "$PORT"
HOST = "0.0.0.0"
RAILWAY = "true"